tf_variables_file: modules/aws_key_upload/variables.tf
execgroup: williaumwu:::demo1-aws_ssh_keys::aws_key_upload
resource_type: aws_ssh_key
resource_name: configo-test
timeout: 300
tf_runtime: tofu:1.9.1
dest_dir: stacks
stack_name: aws_key_upload
